### ISSUE TITLE
How to not override RichAnnotations colours when CSS Feature is enabled

### ISSUE THREAD

**Issue by tkapias** [jugglerchris/rust-html2text#138]
## Introduction

I'm using the html2text example tool to convert Html emails for a TUI email client.

In issue #134, I learned that using the CSS feature/option can hide Html element with `max-height: 0` and `display: none` styles, which is really useful for email preview divs.

But, enabling CSS also overrides the RichAnnotations colours that are defined by design.

## Issue

I would like to use the CSS feature for the layout but without overriding RichAnnotations.

It doesn't look like the overriding was implemented in "examples/html2text.rs" but directly in the library.

How to do that in "examples/html2text.rs"?

**Comment by jugglerchris** [comment]
The CSS feature adds `Colour`/`BgColour` rich annotations which `html2text` uses to override the choices for other annotations in `default_colour_map()`.
