### ISSUE TITLE
API surface

### ISSUE THREAD

**Issue by sftse** [jugglerchris/rust-html2text#150]
It seems that html2text accidentally exposes a lot of its internal details publically.

This leads to semver hazards when developing, an unclear guidance on what can be changed at what costs, overly verbose api docs, misuses of low-level internal apis (with fuzzing false-positives #93 ) and an inability of Rust's visibility checker to point to dead code.

I've made a best-effort attempt to trim the api surface based on my understanding how the crate is supposed to be used  #149

**Comment by jugglerchris** [comment]
Thanks.  Some of those are clearly me thinking about C++-style public rather than Rust's module-scope.

**Comment by sftse** [comment]
Afaik the only thing that can be sensibly done with a `RenderTree` after this change is to pass it unmodified to other api functions. Maybe the only methods except those setting config values that should be exposed on `Config` are `fn string_from_read` and `fn lines_from_read`? Then the only entry points to the library remaining would be the meat of the config done through `TextDecorator`, the built-in options exposed by `Config` and the functions to produce either annotated lines or a string.
