### ISSUE TITLE
bug: Preformatted text wrapping in nested tables causes assertion error.

### ISSUE THREAD

**Issue by JadedBlueEyes** [jugglerchris/rust-html2text#187]
Minimal reproduction:
It seems that a specific combination of nested tables combined with a preformatted text element causes a panic.

```rust
        let html = br#"<div><table><tbody><tr><td><div><table><tbody><tr><td><div><p class="pre">na na na na na na na na na na na na na na na</p></div></td></tr>/<tbody></table></div></td></tr>/<tbody></table></div>"#;
        let _ = crate::config::plain().add_css(r#".pre { white-space: pre; }"#)
        .unwrap()
        .string_from_read(&html[..], 17);
```

```
thread 'tests::css_tests::test_pre_no_wrap' panicked at src\render\text_renderer.rs:302:9:
assertion `left == right` failed
  left: 17
 right: 16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

For now I am working around this by enabling raw mode.

**Comment by jugglerchris** [comment]
Thanks for the test case!
#188 should fix it - I'll try to do a release soon with the fix.
FWIW the error is a debug assertion - it may all work fine in a release build.

**Comment by JadedBlueEyes** [comment]
Thanks for the snappy fix!

Good to know that it's a debug assert. Conveniently for me raw mode produces better output in my particular case!
