### ISSUE TITLE
Applying as a maintainer

### ISSUE THREAD

**Issue by sftse** [jugglerchris/rust-html2text#190]
More than two years ago, we opened our first PR; #64

Since then, html2text has grown from experimental status at [Farsight](https://www.farsight.net) to an incredibly vital component, touching every email we handle. Given its significance, we are committed to supporting it and fixing any bugs we encounter.

Unfortunately, we've already seen some projects die down before being able to support them in a sensible way, we would like to not repeat that mistake and ask you to consider us for co-maintainer. Our profile consists mostly of contributions to file format parsers (CFB, PDF, various mail formats, XLS/XLSX and this crate).

**Comment by jugglerchris** [comment]
Hi,
It's great to hear html2text is being useful, and thanks for the nice contributions so far!

But I'm not sure what would be gained by making you a maintainer?  If I were to stop maintaining the project, you could just maintain your own fork and be no worse off as far as I can tell.  I'm happy to continue to accept PRs and issues.

FWIW I have no plans to stop (I use it for all my personal e-mail too, at least that's HTML) any time soon, though as a spare-time project there are obviously no guarantees!

**Comment by sftse** [comment]
I agree with you that the benefits to me are quite small. This is more a suggestion to increase the bus factor from currently one, to prevent a single bus (or other circumstances) from disrupting the maintenance of the project. I agree that forks are possible, but it can be quite disruptive to have to reorient around a fork, and the old name will remain taken on crates.io.

However, I can understand there are reasons for not wanting to take on co-maintainers.
