### ISSUE TITLE
Support custom rich text decorators

### ISSUE THREAD

**Issue by robinkrahl** [jugglerchris/rust-html2text#24]
Currently, I can either implement a custom `TextDecorator` and produce a string using `from_read_with_decorator`, or I can produce annotated text with `RichDecorator` using `from_read_rich`.  I’d like to be able to implement a custom `TextDecorator` and produce annotated text.  As far as I see, that is not possible at the moment.

What do you think about adding a `from_read_rich_with_decorator` function?

**Comment by jugglerchris** [comment]
That looks like an obviously good idea and missing function to me!

I'd be happy to accept a PR if you're so inclined, or I'll get to it eventually.  My only very minor concern is that the function name ends up rather long, so even better if you have any better ideas than the less than ideal name the existing functions are pointing to.

**Comment by robinkrahl** [comment]
Thanks, I’ll prepare a PR!

I can’t think of a better naming scheme right now.  Maybe it would make
sense to separate setting the decorator and setting the output format?
You could add a simple struct, e. g. Converter, and set the text
decorator when constructing the struct.  Then you could have one method
per output format.  For example:

from_read(s, n) --> Converter::new().convert_to_string(s, n)

from_read_rich(s, n) --> Converter::rich().convert(s, n)

from_read_with_decorator(s, n, d) -->
Converter::with_decorator(d).convert_to_string(s, n)

from_read_rich_with_decorator(s, n, d) -->
Converter::with_decorator(d).convert()

**Comment by jugglerchris** [comment]
That sounds like a good plan, and more future proof.

**Comment by robinkrahl** [comment]
Resolved with #31-
