### ISSUE TITLE
Support definition lists

### ISSUE THREAD

**Issue by robinkrahl** [jugglerchris/rust-html2text#26]
It would be great if you could add support for definition lists:

```
<dl>
  <dt>Topic</dt>
  <dd>Definition</dd>
</dl>
```

<dl>
  <dt>Topic</dt>
  <dd>Definition</dd>
</dl>

The topic could be rendered bold and the definition could be indented by two our four spaces.

**Comment by jugglerchris** [comment]
That sounds like a good case to add, thanks!
