### ISSUE TITLE
Link syntax in markdown

### ISSUE THREAD

**Issue by zakaluka** [jugglerchris/rust-html2text#44]
Hi,

Currently, links are output as [link text][link number].

For example:

```md
This is [a link][1]

[1] https://google.com
```

However, to make this work, a colon is required in the second part of the link:

```md
This is [a link][1]

[1]: https://google.com
```

**Comment by jugglerchris** [comment]
Thanks for the PR and for making sure the tests passed!

While `html2text` isn't specifically trying to output markdown, I'm happy to get closer if the output is still reasonable plain text output.
