### ISSUE TITLE
Feature request: provide the URL of an image

### ISSUE THREAD

**Issue by spencerwi** [jugglerchris/rust-html2text#72]
I've built [a TUI Miniflux client](https://github.com/spencerwi/cliflux) that uses this lib for converting contents of RSS feed entries into something readable in the terminal, and it's great.

The only thing missing is that I'd love a way to just spit out the URL for an image when one is present (or do some other sort of processing with that URL, like giving it to the user in another way). Currently, [the `RichAnnotation::Image` enum member doesn't provide any way to get the image's `src` attribute](https://github.com/jugglerchris/rust-html2text/blob/a7895990c501c13290663bd5d4530c800ba7a792/src/render/text_renderer.rs#L1603-L1604), so I can't actually do that (instead, I either show alt text or nothing).

**Comment by jugglerchris** [comment]
I agree, that's an obvious think to want.  Thanks for the request and matching MR!

**Comment by jugglerchris** [comment]
FYI I've released 0.5.0 with this change.  Thanks again!

**Comment by spencerwi** [comment]
Awesome, I incorporated that release and now my miniflux client is more complete. Thanks again for the merge and release!
