### ISSUE TITLE
Deduplicate whitespace by default

### ISSUE THREAD

**Issue by sftse** [jugglerchris/rust-html2text#77]
The tests indicate that it was intentional for html2text to preserve whitespace, but is there a reason for this? I've run into html that expects the default behavior of browsers that deduplicate whitespace. If this is not deduplicated it messes up the formatting of a larger table.

```
<td style="margin: 0px; padding: 0px;
                    -webkit-print-color-adjust: exact;" class="">Your
                    AT Conference Account is Past Due - Suspension
                    Notice</td>
```

**Comment by jugglerchris** [comment]
Whitespace should only be preserved inside `<pre>` blocks, where it is intentional.
Do you have a complete (ideally relatively small) example which shows the problem?  The fragment above seems to be ok - e.g. no extra space between "Your" and "AT".
```shell
$ target/debug/examples/html2text --width 20
<td style="margin: 0px; padding: 0px;                 
                    -webkit-print-color-adjust: exact;" class="">Your
                    AT Conference Account is Past Due - Suspension
                    Notice</td>
Your AT Conference
Account is Past Due
- Suspension Notice

```

**Comment by jugglerchris** [comment]
I know that there are definitely some cases with excess whitespace - so a simple case showing problems would be very welcome!

**Comment by sftse** [comment]
Updated #76 

When whitespace is not ignored in the table, it forces other text to be broken even when this is unnecessary.

```
──────┬───────────────────────────────────────────────────────────────
Oggett│Your AT Account is Past Due - Suspension Notice                
o:    │                                                               
──────┴───────────────────────────────────────────────────────────────
```

**Comment by jugglerchris** [comment]
Aha, I think I see what's going on.  The place to remove excess whitespace is in `RenderNode::get_size_estimate()` - the result of that is used as part of the calculation for how wide the columns in a table are relative to each other.

Could you please try out the change I've just pushed to branch `issue_77_improve_estimate`?

**Comment by sftse** [comment]
I'll get back to you after the weekend, I don't have access to the example from where I'm at.
Thanks!

**Comment by sftse** [comment]
Looks good

**Comment by jugglerchris** [comment]
@sftse I will probably do a release with this fix at the weekend - let me know if you're desperate for one sooner.
