### ISSUE TITLE
Make links global

### ISSUE THREAD

**Issue by sftse** [jugglerchris/rust-html2text#82]
Links are currently recursively rendered into tables, which can take much more space than the text, distorting the table in the process.

#81 is a prototype how to collect the links globally and only append them at the very end, although you might have a better idea. The PR makes the former `BuilderStack` the new `TextRenderer` which can additionally carry state shared among the stack of renderer.

**Comment by jugglerchris** [comment]
Hi,

Thanks for another contribution!

I like the idea of moving the links to the end - I agree it can sometimes make tables pretty terrible, especially with the links you get these days.

I probably won't get a chance to review the MR until the weekend I'm afraid!

**Comment by jugglerchris** [comment]
Merged, thank you!

**Comment by jugglerchris** [comment]
I've published 0.6.0 with this change.  Thanks again!
