### ISSUE TITLE
Using a parameter of 0 for wrapping length on methods such as render_plain results in infinite allocation up to OOM.

### ISSUE THREAD

**Issue by bingen13** [jugglerchris/rust-html2text#88]
Calling a function like this caused my program to OOM and crash, and took me ages to work out because I didn't know what was causing it:

```async fn print_status(s: &Status) {
    println!(
        "{}",
        html2text::parse(s.content.as_bytes())
            .render_plain(0)
            .into_string()
    );
}

```

**Comment by jugglerchris** [comment]
Oops, that's not a good failure mode!
I guess it should just panic immediately with a width of 0.
