### ISSUE TITLE
Panick at 'attempt to divide by zero'

### ISSUE THREAD

**Issue by mtorromeo** [jugglerchris/rust-html2text#90]
The render table code is susceptible to panicking after attempting to divide by zero, as it just happened to me at this line of code:

```
thread 'main' panicked at 'attempt to divide by zero', [..]/html2text-0.6.0/src/lib.rs:1382:13
```

There are probably more places where this can happen.

Thanks

**Comment by jugglerchris** [comment]
Thanks for the report!
Looking at that line, I guess you have an HTML table with colspan=0?

**Comment by mtorromeo** [comment]
Yes, that is the case where I encountered the problem but looking at the code I think there might be a couple of additional divisions that might panick.

The first one is [the tot_size value](https://github.com/jugglerchris/rust-html2text/blob/f35c8079d4a6c54bc97a20d14b00a56f33c1316d/src/lib.rs#L1391) that is used in a couple of divisions a few lines later.

That line could maybe be replaced with this?
```rs
let tot_size: usize = max(col_sizes.iter().map(|est| est.size).sum(), 1);
```

And then in the same function there a [division by width](https://github.com/jugglerchris/rust-html2text/blob/f35c8079d4a6c54bc97a20d14b00a56f33c1316d/src/lib.rs#L1407) where it might make sense to guard the division like so:
```rs
if width > 0 && usize::MAX / width <= sz.size {
```

What do you think?

**Comment by jugglerchris** [comment]
Thanks for helping to make html2text more robust!

The `tot_size` one seems safe to me - the only way for it to be zero is if all the column sizes are zero - but if so then it'll hit the `if sz.size == 0` case and not do the division.

I *think* the `/ width` is also safe - again the division won't happen if `min_size > width`, but perhaps it could be possible (if not now then later) for `min_size==0` as well.  So I agree that it seems a good idea to handle this - I've pushed a change to set vert_row if width==0 too.

Let me know if you think my reasoning is faulty!

**Comment by jugglerchris** [comment]
I've merged the MR, which has auto-closed the issue - feel free to re-open if you feel it's not fully dealt with it yet!

**Comment by mtorromeo** [comment]
> The `tot_size` one seems safe to me - the only way for it to be zero is if all the column sizes are zero - but if so then it'll hit the `if sz.size == 0` case and not do the division.

That seems fine to me.

Technically, you could have a `tot_size` of zero with no columns of zero size by having an addition overflow the usize variable back to 0, but I recognize that it's an unreasonable occurrence.

Thanks for the fixes!
